micronaut:
  application:
    name: todotopiaApi
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
        path: "/sign-in"
    token:
      enabled: true
      roles-name: "roles"
      name-key: "sub"
      roles-separator:
      jwt:
        generator:
          access-token:
            expiration: 604800
        bearer:
          enabled: true
          header-name: "Authorization"
          prefix: "Bearer"
        signatures:
          secret:
            generator:
              secret: ${TODOTOPIA_API_JWT_TOKEN}
              jws-algorithm: HS512
              base64: false

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    db-type: postgresql
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver
    schema-generate: none
    url: jdbc:postgresql://localhost:5432/todotopia
    username: admin
    password: password

jpa:
  default:
    properties:

flyway:
  datasources:
    default:
      enabled: true
